// @ts-check
// SPDX-License-Identifier: MIT
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// `site` is the canonical URL the build uses for absolute links
// (sitemap, OpenGraph, canonical tags, JSON-LD). Set curated.config.ts
// → `siteUrl` and run `open-curated build` — this file is read by
// Astro directly.
//
// The sitemap itself is generated by a custom Astro endpoint at
// `src/pages/sitemap.xml.ts` rather than `@astrojs/sitemap`, so the
// public URL is exactly `/sitemap.xml` (no `-index.xml` suffix).
export default defineConfig({
  site: process.env.SITE_URL || 'https://example.com',
  trailingSlash: 'ignore',
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    format: 'directory',
  },
});
