packages:
  - packages/core
  - packages/astro
  - packages/cli
  - packages/starlight
  - apps/example
  - apps/docs

auditConfig:
  ignoreCves:
    - GHSA-jmr9-qjv8-65gv

linkWorkspacePackages: true

overrides:
  sharp@<0.35.0: '>=0.35.0'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
  '@opentelemetry/core@<2.8.0': '>=2.8.0'

preferWorkspacePackages: true
