import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import {
  type AppRecord,
  type CuratedConfig,
  normalizeAppRecord,
  parseAppYaml,
  toIndexApp,
} from "./schema.js";
import { loadConfig } from "./config.js";

/**
 * The full payload written to data/generated/apps.full.json.
 * Carries every normalized record, regardless of visibility.
 */
export interface AppsFullPayload {
  schemaVersion: number;
  generatedAt: string;
  totalApps: number;
  visibleApps: number;
  apps: Array<Record<string, unknown>>;
}

/**
 * The slim payload written to data/generated/apps.index.json.
 * Carries only what list and search pages need.
 */
export interface AppsIndexPayload {
  schemaVersion: number;
  generatedAt: string;
  totalApps: number;
  apps: Array<Record<string, unknown>>;
}

/**
 * The TS file written to src/data/config.ts. Sites import this for
 * a typed view of curated.config.ts. Auto-generated; do not edit.
 */
export interface SiteConfigTsInput {
  name: string;
  tagline: string;
  description: string;
  siteUrl: string;
  repoUrl: string;
  itemLabel: string;
}

export function buildSiteConfigTs(input: SiteConfigTsInput): string {
  return `/**
 * AUTO-GENERATED by grove build-data — do not edit by hand.
 * Re-run \`grove build-data\` after changing curated.config.ts.
 */

export type SiteConfig = {
  name: string;
  tagline: string;
  description: string;
  siteUrl: string;
  repoUrl: string;
  itemLabel: string;
};

export const siteConfig: SiteConfig = {
  name: ${JSON.stringify(input.name)},
  tagline: ${JSON.stringify(input.tagline)},
  description: ${JSON.stringify(input.description)},
  siteUrl: ${JSON.stringify(input.siteUrl)},
  repoUrl: ${JSON.stringify(input.repoUrl)},
  itemLabel: ${JSON.stringify(input.itemLabel)},
};
`;
}

/**
 * Read every apps/*.yml in the project, normalize, and build:
 *  - data/generated/apps.full.json   (full records, all visibility)
 *  - data/generated/apps.index.json  (slim, visible-only)
 *  - data/generated/apps.json        (compatibility alias of apps.full.json)
 *  - src/data/config.ts              (typed view of curated.config.ts)
 *
 * Returns a small summary; throws on schema errors.
 */
export interface BuildDataResult {
  totalApps: number;
  visibleApps: number;
  fullPath: string;
  indexPath: string;
  aliasPath: string;
  configTsPath: string;
  errors: string[];
}

export async function buildData(
  cwd = process.cwd(),
  config?: CuratedConfig,
): Promise<BuildDataResult> {
  const cfg = config ?? (await loadConfig(cwd));
  const appsDir = resolve(cwd, cfg.paths.appsDir);
  const outDir = resolve(cwd, cfg.paths.generatedDir);
  await mkdir(outDir, { recursive: true });

  let entries: string[] = [];
  try {
    entries = await readdir(appsDir);
  } catch {
    entries = [];
  }
  const files = entries.filter((f) => f.endsWith(".yml")).sort();

  const apps: AppRecord[] = [];
  const errors: string[] = [];
  for (const file of files) {
    const fileSlug = basename(file, ".yml");
    try {
      const text = await readFile(join(appsDir, file), "utf8");
      const raw = parseAppYaml(text, fileSlug);
      const app = normalizeAppRecord(raw, fileSlug);
      if (app.slug !== fileSlug) {
        app.slug = fileSlug;
      }
      apps.push(app);
    } catch (err) {
      errors.push(`${file}: ${(err as Error).message}`);
    }
  }
  if (errors.length > 0) {
    const e = new Error(`build-data failed: ${errors.length} schema error(s)`);
    (e as Error & { details?: string[] }).details = errors;
    throw e;
  }

  apps.sort((a, b) => {
    const sa = a.stars ?? 0;
    const sb = b.stars ?? 0;
    if (sb !== sa) return sb - sa;
    return (a.name ?? "").localeCompare(b.name ?? "");
  });

  const indexApps = apps
    .map((app) => toIndexApp(app))
    .filter((a) => a.visibility !== "hide");

  const generatedAt = new Date().toISOString();
  const fullPayload: AppsFullPayload = {
    schemaVersion: 1,
    generatedAt,
    totalApps: apps.length,
    visibleApps: indexApps.length,
    apps: apps as unknown as Array<Record<string, unknown>>,
  };
  const indexPayload: AppsIndexPayload = {
    schemaVersion: 1,
    generatedAt,
    totalApps: indexApps.length,
    apps: indexApps as unknown as Array<Record<string, unknown>>,
  };

  const fullPath = join(outDir, "apps.full.json");
  const indexPath = join(outDir, "apps.index.json");
  const aliasPath = join(outDir, "apps.json");
  await writeFile(fullPath, JSON.stringify(fullPayload, null, 2), "utf8");
  await writeFile(indexPath, JSON.stringify(indexPayload, null, 2), "utf8");
  await writeFile(aliasPath, JSON.stringify(fullPayload, null, 2), "utf8");

  const configTsPath = resolve(cwd, "src/data/config.ts");
  const configTs = buildSiteConfigTs({
    name: cfg.name,
    tagline: cfg.tagline,
    description: cfg.description ?? cfg.tagline,
    siteUrl: cfg.siteUrl ?? "https://example.com",
    repoUrl: cfg.repoUrl ?? "",
    itemLabel: cfg.itemLabel,
  });
  await writeFile(configTsPath, configTs, "utf8");

  return {
    totalApps: apps.length,
    visibleApps: indexApps.length,
    fullPath,
    indexPath,
    aliasPath,
    configTsPath,
    errors,
  };
}
