---
title: Introduction
description: Grove is a file-first publishing system for structured knowledge. One source of truth — many useful outputs.
---

Grove is a **file-first publishing system for structured knowledge**.

You write the source of truth — YAML records, Markdown bodies, taxonomy files. Grove publishes it into a coordinated set of human- and machine-readable outputs and keeps everything in sync.

> Maintain structured knowledge in files. Grove publishes it into useful human- and machine-readable outputs and keeps everything in sync.

## One piece of content → many useful outputs

A single record in `data/records/<slug>.yml` becomes, all at once:

| Output | Audience |
|---|---|
| A page on your site | Visitors browsing the directory |
| An entry in `sitemap.xml` | Search engines |
| An entry in `llms.txt` | AI assistants and crawlers |
| A JSON-LD `SoftwareSourceCode` block | Google rich results |
| A satori-rendered OG card at `public/og/<page>.png` | Slack, LinkedIn, Discord |
| A row in `data/generated/records.json` | Anything consuming your dataset |

The same loop applies to taxonomy, decisions, collections, and standalone content pages. Files stay in your repo; outputs follow.

## When to use Grove

Grove is for teams who want **the source of truth to be a human-readable file in their repo**, and who want a static, deploy-anywhere output. Typical fits:

- Curated catalogs of open-source projects, libraries, agents, or tools.
- Research collections — papers, datasets, working groups.
- Community knowledge bases — guides, essays, decisions.
- Industry ecosystems — companies, agencies, foundations.
- Editorial knowledge bases — articles, podcasts, courses.

Grove is **not** a CMS, not a database, not a SaaS. Editors don't log in. PRs are the change-of-record.

## Static-first, no runtime

Every output is generated by `grove check` or the implicit Astro build:

- HTML pages
- `sitemap.xml`, `robots.txt`, `llms.txt`, `llms-full.txt`
- `data/generated/records.full.json`, `records.index.json`, `records.json`, `site-config.json`
- `public/og/<page>.png` (satori-rendered social cards)
- The README block bounded by sentinels

There is no runtime server, no database, no event loop. The build is the system.

## Authoring tools

- **`pnpm dlx @grove-dev/cli@latest init my-space`** — scaffolds a space from the canonical template.
- **`grove check`** — validates records, regenerates outputs, runs `astro check`.
- **`grove sync github`** — refreshes stars/forks/language/topics/license and per-record health.
- **`grove sync contributors`** — aggregates contributor counts.
- **`grove readme generate`** — renders the awesome-list block in `README.md`.

See [reference/cli](/reference/cli/) for the full list, every option, and what each command writes.

## Ready to start?

- **[Quickstart](/start-here/quickstart/)** — ten minutes to a working Grove site.
- **[Why Grove](/start-here/why-grove/)** — what problem this solves and what it deliberately doesn't.
- **[Mental model](/start-here/mental-model/)** — files, derived outputs, refreshed facts.
