#!/usr/bin/env node
// SPDX-License-Identifier: MIT

/**
 * build-llms.mjs — emit `public/llms-full.txt` (per-record
 * markdown mirror) only.
 *
 * `public/llms.txt` is a static file committed to the template —
 * it does NOT get regenerated by this script. The build pipeline
 * treats the committed version as the canonical, hand-curated
 * LLM-facing index. The script only refreshes the per-record
 * `llms-full.txt` from the latest `data/generated/records.full.json`.
 *
 * This is intentional: openapps' `llms.txt` is also a
 * hand-curated 30+ line document, not an auto-generated stub.
 *
 * Usage:  node scripts/build-llms.mjs
 */
import { mkdir, readFile, writeFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SOURCE = join(ROOT, "data", "generated", "records.full.json");
const SITE_CONFIG = join(ROOT, "data", "generated", "site-config.json");
const OUT_DIR = join(ROOT, "public");
const FULL = join(OUT_DIR, "llms-full.txt");

function compactStars(n) {
  if (typeof n !== "number" || !Number.isFinite(n)) return "—";
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1_000) {
    const k = n / 1_000;
    return (k >= 10 ? Math.round(k).toString() : k.toFixed(1).replace(/\.0$/, "")) + "k";
  }
  return n.toString();
}

function relativeTime(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.valueOf())) return "—";
  const days = Math.floor((Date.now() - d.valueOf()) / 86_400_000);
  if (days === 0) return "today";
  if (days === 1) return "1 day ago";
  if (days < 30) return `${days} days ago`;
  if (days < 365) return `${Math.floor(days / 30)} months ago`;
  return `${Math.floor(days / 365)} years ago`;
}

function buildFullTxt(records, site, routeSlug) {
  const lines = [];
  lines.push(`# ${site.replace(/^https?:\/\//, "")} — full directory`);
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Records: ${records.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const r of records) {
    const name = r.name ?? r.title ?? r.slug;
    const stack = r.stack ?? (Array.isArray(r.stacks) ? r.stacks.join(", ") : "");
    const platforms = Array.isArray(r.platforms) ? r.platforms.join(", ") : "";
    const tags = Array.isArray(r.tags) ? r.tags.join(", ") : "";
    const stars = compactStars(
      r.stars ?? r.github?.stars ?? r.github?.repository?.stargazers_count ?? 0,
    );
    const updated = relativeTime(
      r.lastCommitAt ??
        r.github?.pushedAt ??
        r.github?.repository?.pushed_at ??
        null,
    );
    const repoUrl = r.repoUrl ?? r.links?.github ?? "";
    const url = `${site.replace(/\/$/, "")}/${routeSlug}/${r.slug}`;
    const desc = r.description ?? "";

    lines.push(`## ${name}`);
    lines.push("");
    if (desc) lines.push(desc);
    lines.push("");
    lines.push(`- **URL**: ${url}`);
    if (repoUrl) lines.push(`- **Repository**: ${repoUrl}`);
    if (stack) lines.push(`- **Stack**: ${stack}`);
    if (platforms) lines.push(`- **Platforms**: ${platforms}`);
    if (r.category) lines.push(`- **Category**: ${r.category}`);
    if (tags) lines.push(`- **Tags**: ${tags}`);
    if (r.license) lines.push(`- **License**: ${r.license}`);
    lines.push(`- **Stars**: ${stars}`);
    lines.push(`- **Last commit**: ${updated}`);
    lines.push("");
    if (Array.isArray(r.bestFor) && r.bestFor.length) {
      lines.push("**Best for:**");
      for (const b of r.bestFor) lines.push(`- ${b}`);
      lines.push("");
    }
    if (Array.isArray(r.whyListed) && r.whyListed.length) {
      lines.push("**Why listed:**");
      for (const w of r.whyListed) lines.push(`- ${w}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }
  return lines.join("\n");
}

async function main() {
  if (!(await access(SOURCE).then(() => true).catch(() => false))) {
    console.error(`No ${SOURCE} found. Run \`grove generate\` first.`);
    process.exit(1);
  }
  const raw = JSON.parse(await readFile(SOURCE, "utf8"));
  const siteConfig = JSON.parse(await readFile(SITE_CONFIG, "utf8"));
  const site =
    process.env.GROVE_SITE ??
    process.env.SITE_URL ??
    siteConfig.siteUrl ??
    "https://example.com";
  const routeSlug = siteConfig.blueprintConfig?.routeSlug ?? "projects";
  const records = (raw.records ?? []).filter(
    (r) => r.visibility !== "hide" && r.visibility !== "remove",
  );

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(FULL, buildFullTxt(records, site, routeSlug), "utf8");
  console.log(`[llms] ${records.length} indexed → ${FULL}`);
  console.log(`[llms] public/llms.txt is committed (NOT regenerated) — see scripts/build-llms.mjs`);
}

main().catch((err) => {
  console.error("build-llms failed:", err);
  process.exit(1);
});
