// @ts-check
// SPDX-License-Identifier: MIT
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// `site` is the canonical URL the build uses for absolute links
// (sitemap, OpenGraph, canonical tags, JSON-LD). The CLI injects
// `grove.config.ts` → `site.url` at scaffold time, but it can also
// be overridden per-build via the `SITE_URL` env var.
//
// The sitemap is generated by the CLI's `grove sitemap` command
// into `public/sitemap.xml`; the public URL is exactly `/sitemap.xml`
// (no `-index.xml` suffix).
export default defineConfig({
  site: process.env.SITE_URL || 'https://example.com',
  trailingSlash: 'ignore',
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    format: 'directory',
  },
});
